SQLALCHEMY_DATABASE_URI = 'sqlite:///databases/societies.db'
SECRET_KEY = 'pHKQV3SDk56zPNsInn_ZZ1yv_K_hAMJ4W5YtyTykirs='
PASSWORD_RESET_KEY = 'fXVN4j-wZXyTReqfVdd3Obox_xPpm6AbLNYMdn-iI3o'
CAPTCHA_SECRET_KEY = '6Lfj_ZoeAAAAAHgieWj7OB6MK06rvhm-gPOerSWP'